### ISSUE TITLE
Add support for building on macOS/darwin

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/kraftkit#266]
### Feature request summary

Kraftkit should be usable on macOS-based systems. The code is mostly OS-agnostic so changes should be minimal.
The focus should be on x86_64 first, and then moved to arm.

The task of successfully building and running unikernels needs to be tackled in the main repository first.

### Related architectures

amd64, arm64

### Related platforms

macOS

### Additional context

Several pieces of work need to be done in order to accommodate the new platform:

- [x] https://github.com/unikraft/unikraft/issues/785
- [x] https://github.com/unikraft/kraftkit/issues/30
- [ ] https://github.com/unikraft/kraftkit/issues/673
- [x] #674
- [x] #675
- [ ] #678
